name: Build and Push Docker image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      run: docker build . -t ghcr.io/flydrm/team-manage:latest

    - name: Push Docker image
      run: docker push ghcr.io/flydrm/team-manage:latest
